baseURL = "https://mrinmaydev.github.io/principles.github.io/"
languageCode = "en-us"
title = "Principles"
theme="archie"
copyright = "© Principles by Mrinmay Dev Sarma"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
#relativeURLs = true
#canonifyURLs = true

paginate=10 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Ordinary everyday things"

# Social Tags

#[[params.social]]
#name = "GitHub"
#icon = "github"
#url = "https://github.com/athul/archie"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/athulcajay/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


